CC=gcc
CFLAGS=-Wall
DEPS=fileio.h

all: head2 head3 csv_avg

head2: head2.o fileio.o
	$(CC) $(CFLAGS) head2.o fileio.o -o head2

head3: head3.o fileio.o
	$(CC) $(CFLAGS) head3.o fileio.o -o head3

csv_avg: csv_avg.o fileio.o
	$(CC) $(CFLAGS) csv_avg.o fileio.o -o csv_avg

%.o: %.c $(DEPS)
	$(CC) $(CFLAGS) -c -o $@ $<

